-- MySQL Script generated by MySQL Workbench
-- 11/16/16 13:28:56
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema clickbaitDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema clickbaitDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `clickbaitDB` DEFAULT CHARACTER SET utf8 ;
USE `clickbaitDB` ;

-- -----------------------------------------------------
-- Table `clickbaitDB`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clickbaitDB`.`USER` (
  `userID` INT NOT NULL AUTO_INCREMENT,
  `userName` VARCHAR(24) NOT NULL,
  `userEmail` VARCHAR(45) NOT NULL,
  `userPassword` VARCHAR(60) NOT NULL,
  `birthDate` VARCHAR(10) NOT NULL,
  `infos` VARCHAR(200) NULL,
  PRIMARY KEY (`userID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clickbaitDB`.`PLAYLIST`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clickbaitDB`.`PLAYLIST` (
  `playlistID` INT NOT NULL AUTO_INCREMENT,
  `playlistName` VARCHAR(45) NOT NULL,
  `dirSrc` VARCHAR(100) NOT NULL,
  `booleanPublic` TINYINT(1) NOT NULL,
  `genPrivateCode` VARCHAR(32) NULL,
  PRIMARY KEY (`playlistID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clickbaitDB`.`USER_PLAYLIST`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clickbaitDB`.`USER_PLAYLIST` (
  `userID` INT NOT NULL,
  `playlistID` INT NOT NULL,
  INDEX `fk_USER_PLAYLIST_USER_idx` (`userID` ASC),
  INDEX `fk_USER_PLAYLIST_PLAYLIST1_idx` (`playlistID` ASC),
  CONSTRAINT `fk_USER_PLAYLIST_USER`
    FOREIGN KEY (`userID`)
    REFERENCES `clickbaitDB`.`USER` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USER_PLAYLIST_PLAYLIST1`
    FOREIGN KEY (`playlistID`)
    REFERENCES `clickbaitDB`.`PLAYLIST` (`playlistID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clickbaitDB`.`MEDIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clickbaitDB`.`MEDIA` (
  `mediaID` INT NOT NULL AUTO_INCREMENT,
  `mediaTitle` VARCHAR(45) NOT NULL,
  `mediaDescription` VARCHAR(80) NOT NULL,
  `mediaSrc` VARCHAR(100) NOT NULL,
  `booleanVideo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`mediaID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clickbaitDB`.`PLAYLIST_MEDIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clickbaitDB`.`PLAYLIST_MEDIA` (
  `playlistID` INT NOT NULL,
  `mediaID` INT NOT NULL,
  INDEX `fk_PLAYLIST_MEDIA_PLAYLIST1_idx` (`playlistID` ASC),
  INDEX `fk_PLAYLIST_MEDIA_MEDIA1_idx` (`mediaID` ASC),
  CONSTRAINT `fk_PLAYLIST_MEDIA_PLAYLIST1`
    FOREIGN KEY (`playlistID`)
    REFERENCES `clickbaitDB`.`PLAYLIST` (`playlistID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PLAYLIST_MEDIA_MEDIA1`
    FOREIGN KEY (`mediaID`)
    REFERENCES `clickbaitDB`.`MEDIA` (`mediaID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clickbaitDB`.`USER_MEDIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clickbaitDB`.`USER_MEDIA` (
  `userID` INT NOT NULL,
  `mediaID` INT NOT NULL,
  `booleanLike` TINYINT(1) NOT NULL,
  `comment` VARCHAR(200) NULL,
  INDEX `fk_USER_MEDIA_USER1_idx` (`userID` ASC),
  INDEX `fk_USER_MEDIA_MEDIA1_idx` (`mediaID` ASC),
  CONSTRAINT `fk_USER_MEDIA_USER1`
    FOREIGN KEY (`userID`)
    REFERENCES `clickbaitDB`.`USER` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USER_MEDIA_MEDIA1`
    FOREIGN KEY (`mediaID`)
    REFERENCES `clickbaitDB`.`MEDIA` (`mediaID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
