-- MySQL Script generated by MySQL Workbench
-- 11/28/16 09:40:34
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema clickbaitdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema clickbaitdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `clickbaitdb` DEFAULT CHARACTER SET utf8 ;
USE `clickbaitdb` ;

-- -----------------------------------------------------
-- Table `clickbaitdb`.`media`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clickbaitdb`.`media` (
  `mediaID` INT(11) NOT NULL AUTO_INCREMENT,
  `mediaTitle` VARCHAR(45) NOT NULL,
  `mediaDescription` VARCHAR(80) NOT NULL,
  `mediaSrc` VARCHAR(100) NOT NULL,
  `booleanVideo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`mediaID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `clickbaitdb`.`playlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clickbaitdb`.`playlist` (
  `playlistID` INT(11) NOT NULL AUTO_INCREMENT,
  `playlistName` VARCHAR(45) NOT NULL,
  `dirSrc` VARCHAR(100) NOT NULL,
  `booleanPublic` TINYINT(1) NOT NULL,
  `genPrivateCode` VARCHAR(32) NULL DEFAULT NULL,
  PRIMARY KEY (`playlistID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `clickbaitdb`.`playlist_media`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clickbaitdb`.`playlist_media` (
  `playlistID` INT(11) NOT NULL,
  `mediaID` INT(11) NOT NULL,
  INDEX `fk_PLAYLIST_MEDIA_PLAYLIST1_idx` (`playlistID` ASC),
  INDEX `fk_PLAYLIST_MEDIA_MEDIA1_idx` (`mediaID` ASC),
  CONSTRAINT `fk_PLAYLIST_MEDIA_MEDIA1`
    FOREIGN KEY (`mediaID`)
    REFERENCES `clickbaitdb`.`media` (`mediaID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PLAYLIST_MEDIA_PLAYLIST1`
    FOREIGN KEY (`playlistID`)
    REFERENCES `clickbaitdb`.`playlist` (`playlistID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `clickbaitdb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clickbaitdb`.`user` (
  `userID` INT(11) NOT NULL AUTO_INCREMENT,
  `userName` VARCHAR(24) NOT NULL,
  `userEmail` VARCHAR(45) NOT NULL,
  `userPassword` VARCHAR(60) NOT NULL,
  `birthDate` VARCHAR(10) NOT NULL,
  `infos` VARCHAR(200) NULL DEFAULT NULL,
  `genStringID` VARCHAR(16) NOT NULL,
  `emailConfirmed` TINYINT(1) NOT NULL,
  PRIMARY KEY (`userID`),
  UNIQUE INDEX `genStringID_UNIQUE` (`genStringID` ASC),
  UNIQUE INDEX `userID_UNIQUE` (`userID` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `clickbaitdb`.`user_media`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clickbaitdb`.`user_media` (
  `userID` INT(11) NOT NULL,
  `mediaID` INT(11) NOT NULL,
  `booleanLike` TINYINT(1) NOT NULL,
  `comment` VARCHAR(200) NULL DEFAULT NULL,
  INDEX `fk_USER_MEDIA_USER1_idx` (`userID` ASC),
  INDEX `fk_USER_MEDIA_MEDIA1_idx` (`mediaID` ASC),
  CONSTRAINT `fk_USER_MEDIA_MEDIA1`
    FOREIGN KEY (`mediaID`)
    REFERENCES `clickbaitdb`.`media` (`mediaID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USER_MEDIA_USER1`
    FOREIGN KEY (`userID`)
    REFERENCES `clickbaitdb`.`user` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `clickbaitdb`.`user_playlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clickbaitdb`.`user_playlist` (
  `userID` INT(11) NOT NULL,
  `playlistID` INT(11) NOT NULL,
  INDEX `fk_USER_PLAYLIST_USER_idx` (`userID` ASC),
  INDEX `fk_USER_PLAYLIST_PLAYLIST1_idx` (`playlistID` ASC),
  CONSTRAINT `fk_USER_PLAYLIST_PLAYLIST1`
    FOREIGN KEY (`playlistID`)
    REFERENCES `clickbaitdb`.`playlist` (`playlistID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USER_PLAYLIST_USER`
    FOREIGN KEY (`userID`)
    REFERENCES `clickbaitdb`.`user` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;